spring.application.name=plataform
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db
spring.datasource.username=devuser
spring.datasource.password=devpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs para debug
logging.level.root=INFO
logging.level.com.agenda.plataform=DEBUG
logging.level.org.springframework.security=DEBUG
