name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: agenda
          POSTGRES_USER: agenda
          POSTGRES_PASSWORD: agenda
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U agenda -d agenda"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # muito importante: esperar o postgres ficar pronto
      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            nc -z localhost 5432 && echo "Postgres is up!" && exit 0
            echo "Waiting for Postgres..."
            sleep 2
          done
          echo "Postgres failed to start"
          exit 1

      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/agenda
          SPRING_DATASOURCE_USERNAME: agenda
          SPRING_DATASOURCE_PASSWORD: agenda
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        run: ./mvnw -B verify
